version: '3.3'

services:
  
  # web container - runs the django app
  web:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app/
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    # ensures that docker compose always displays log output
    tty: true
    stdin_open: true
