version: '3.3'

services:
  
  # web container - runs the django app
  web:
    build: .
    image: personal_website_web:latest
    ports:
      - 8000:8000
    container_name: django_web
    volumes:
      - .:/app/
    command: >
      sh -c "python manage.py makemigrations &&
            python manage.py migrate &&
            python manage.py seed --mode=seed_posts &&
            python manage.py seed --mode=seed_projects &&
            python manage.py seed --mode=seed_superuser &&
            python manage.py runserver 0.0.0.0:8000"
    # ensures that docker compose always displays log output
    tty: true
    stdin_open: true
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello
      - POSTGRES_PASSWORD=pw
      - POSTGRES_DB=django_dev_db

volumes:
  postgres_data: