# Generated by Django 4.2.1 on 2023-05-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='header_img',
            field=models.URLField(max_length=500),
        ),
    ]
