# Generated by Django 4.2.1 on 2023-05-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_website', '0002_alter_blogpost_header_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(max_length=5000),
        ),
    ]
