# Generated by Django 4.2.1 on 2023-05-31 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_website', '0009_alter_blogpost_category_alter_blogpost_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('meta_data', models.JSONField()),
                ('content', models.TextField(blank=True, max_length=5000, null=True)),
            ],
        ),
    ]
