# Generated by Django 4.2.1 on 2023-06-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_website', '0010_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='meta_data',
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ManyToManyField(blank=True, to='app_website.category'),
        ),
        migrations.AddField(
            model_name='project',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
