# Generated by Django 4.2.1 on 2023-06-02 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_website', '0012_skills_remove_project_skills_project_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='category',
            new_name='categories',
        ),
    ]
