# Generated by Django 4.2.1 on 2023-06-02 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_website', '0013_rename_category_project_categories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
    ]
