# Generated by Django 4.2.1 on 2023-06-02 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_website', '0016_project_featured_project_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='categories',
        ),
    ]
