# Generated by Django 4.2.1 on 2023-06-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_website', '0017_remove_project_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='header_img_path',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
