# Generated by Django 4.2.1 on 2023-06-07 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_website', '0020_alter_blogpost_posted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='author',
        ),
    ]
