# Generated by Django 4.2.1 on 2023-06-07 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_website', '0021_remove_blogpost_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
