# Generated by Django 4.2.1 on 2023-06-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_website', '0024_alter_blogpost_content_alter_blogpost_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='published',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
