# Generated by Django 4.2.1 on 2023-06-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_website', '0025_blogpost_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=500)),
                ('subscribed', models.BooleanField(default=False)),
            ],
        ),
    ]
