# Generated by Django 4.2.1 on 2023-06-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_website', '0027_rename_subscribers_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='confirmation_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
